# Generated by Django 2.2.5 on 2019-09-18 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
    ]
