# Generated by Django 2.2.5 on 2019-09-20 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0002_remove_user_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bench', models.DecimalField(decimal_places=2, max_digits=6)),
                ('squat', models.DecimalField(decimal_places=2, max_digits=6)),
                ('deadlift', models.DecimalField(decimal_places=2, max_digits=6)),
                ('flexScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flexapp.UserCredentials'),
        ),
    ]
