# Generated by Django 2.2.5 on 2019-09-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0003_auto_20190920_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCredentials',
            new_name='UserCredential',
        ),
    ]
