# Generated by Django 2.2.5 on 2019-09-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0005_auto_20190927_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
