# Generated by Django 2.2.5 on 2019-10-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0006_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredential',
            name='username',
            field=models.CharField(default=models.EmailField(max_length=100, unique=True), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usercredential',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
