# Generated by Django 2.2.5 on 2019-10-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0007_auto_20191011_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercredential',
            old_name='creation_date',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usercredential',
            name='username',
        ),
        migrations.AddField(
            model_name='usercredential',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
