# Generated by Django 2.2.5 on 2019-10-23 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flexapp', '0011_auto_20191018_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentries',
            old_name='exercise',
            new_name='userExercise',
        ),
        migrations.RenameField(
            model_name='userexercise',
            old_name='set',
            new_name='sets',
        ),
        migrations.AddField(
            model_name='userexercise',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
