# Generated by Django 2.2.5 on 2019-10-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexapp', '0013_auto_20191023_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexercise',
            name='sets',
        ),
    ]
